version: '3.4'
services:
  nginx:
    build         : requirements/nginx
    image         : nginx
    container_name: nginx
    restart       : on-failure
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend
    env_file:
      - .env
    ports:
      - 443:443
  wordpress:
    build         : requirements/wordpress
    image         : wordpress
    container_name: wordpress
    restart       : on-failure
    depends_on:
       - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend
      - backend
    env_file:
      - .env

  mariadb:
    build         : requirements/mariadb
    image         : mariadb
    container_name: mariadb
    restart       : on-failure
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env

volumes:
    wp_data:
      driver: local
      driver_opts:
        type  : none
        o     : bind
        device: /home/iyamada/data/wordpress
    db_data:
      driver: local
      driver_opts:
        type  : none
        o     : bind
        device: /home/iyamada/data/mariadb

networks:
  frontend:
  backend:
